### ISSUE TITLE
Feature request: templated "quick install" option for VMs

### ISSUE THREAD

**Issue by yzgyyang** [outpaddling/desktop-installer#15]
I've encountered a lot of FreeBSD newcomers over the past few years, who are willing to "try it out" in a Virtualbox VM, so I think a fully-templated install mode could benefit them - simply select one option at the start, confirm triple warnings about "If you are really on a fresh Virtualbox VM and don't care about anything?", and then all the options are pre-selected to give the user a usable desktop with no further interaction (since we limited it to Virtualbox, the video setting/sound selections can be omitted, and I feel like we can just dictate the rest of the options if we are sure the user just wanted to "try it out").

Please let me know your thoughts, thanks!

**Comment by outpaddling** [comment]
This is in-line with other interface improvements I have planned, such as continuation from a previous run.  Automating to this extent will require some invasive changes, though, and right now I'm avoiding that due to time constraints and the desire to improve robustness first.  I'll take this suggestion into consideration when I have time for a more extensive rework of the interface.

**Comment by outpaddling** [comment]
Closing this issue since plans to move in this direction already exist.
