### ISSUE TITLE
X11 Reconfiguration is for the root user

### ISSUE THREAD

**Issue by yzgyyang** [outpaddling/desktop-installer#18]
Hi Jason,

During the "Reconfigure X11 and desktop?" step, the script seems to be setting the configuration up for root under `/root/.xinitrc` even if I am under a normal user running with `sudo desktop-installer`. Can we use something like `${SUDO_USER}` to get the real user?

I was testing a KDE5 installation in a Virtualbox VM if it helps. Thanks!

**Comment by outpaddling** [comment]
I'm not sure this will work reliably due to possible xauth issues running under su + I would want to be consistent about where the .xinitrc is written.  I'd be more inclined to add a check to warn users about running under su or sudo.  I think for desktop-installer it's best to log in directly as root, which of course should be avoided once the system is fully configured.

**Comment by outpaddling** [comment]
Added a warning if running under su or sudo, advising the user to run under a direct root login on a text console.

**Comment by yzgyyang** [comment]
Thanks! A warning is good enough (as I didn't know root is preferred over sudo) ;)
