### ISSUE TITLE
Installation KDE5 on VMware VM FreeBSD 13.1 ended in unreadable test of X11

### ISSUE THREAD

**Issue by QuGeorge** [outpaddling/desktop-installer#26]
My target is creating a VMware VM running on FreeBSD 13.1 with KDE5 as dekstop environment (I'm rather new to FreeBSD).

First I made a FreeBSD 13.1 VM on my MacBook Pro with VMware Fusion (12.2.4) using the FreeBSD-13.1-RELEASE-amd64-disc1.iso. This succeeded well using the BSD Installer and the BSD Handbook.

Second I used the Acadix desktop-installer as a tool for installing KDE (having assigned to the VM 4GB memory, 2 processors, 60GB HD). The whole procedure of the desktop-installer worked well, including the 694 packages of KDE5, sddm, XF86-video-vmware, and ending by the urgent suggestion to test the X11 environment. Thereby the instruction that I should end the test by a logout, en not by shutting down the system.

When I accepted this by 'y' a nice screen appeared, but the windows, the texts, and the mouse-cursor were so small that I could impossibly figure out what tot do. I tried to change the resolution of the screen, but this didn't help. I also couldn't figure out how to logout (having only configured 'root' as user). On a KDE-forum I found the suggestion to do a CTR-Alt-Backspace. As a result appeared a very small login-window but clicking on something there the whole screen turned black. When nothing helped to remedy this the only way out was to shut down the VM.

Before trying a restart I'll be glad to recieve suggestions about what tot do without corrupting what already has been installed correctly.

Regards
George

**Comment by outpaddling** [comment]
Sorry for the delayed response, I've had some problems with Github notifications and wasn't aware of this issue until now.
It sounds like you have a Retina or similar high-res display.  I don't use VMWare, but in VirtualBox, there is a scale factor setting for this issue.  Normally setting it to 2 will give a reasonable resolution.
The black screen issue is separate.  There was a recent xorg update that caused a similar problem recently, and it has been fixed.
If you are still having trouble, feel free to reopen this issue.
Thanks for the report!

**Comment by QuGeorge** [comment]
Dear Jason Bacon,

Thank you for your delayed response! After some time of waiting for a response I created a fresh FreeBSD 13.1 VM, in order to have it ready for a new try with the desktop-installer. Thereafter, the working season started, leaving me hardly any time for working on FreeBSD. 
Now, your response encourages me to make a new attempt next week (Christmas holiday!). In this connection I would like to ask your advice. The reason of creating a FreeBSD VM is, that my NAS (operating on TrueNas) makes backups on a FreeBSD-filesystem formatted HD. I would like to be able te read this HD independently from this NAS. Therefore I could probably also do with a simpler desktop manager than KDE 5. My question is now: would you recommend me to try one of the simpler dektop managers that the desktop installer offers? 

I don’t know if I have to reopen the issue, nor do I see how to do that. In any case, when a new try ends again in some trouble I could always open a new issue. You will also hear from me when the next attempt is a succes. 

Thanks again, and regards,
George

**Comment by outpaddling** [comment]
You should see a "Reopen" button at the bottom of this page.  Perhaps you are not logged into Github? Of the lightweight desktops, XFCE is probably the most mature and stable.  I use Lumina myself because it is faster, more intuitive, and more appealing than the others in my view.  It does have some (mainly cosmetic) issues that I simply tolerate.  LXDE is no longer developed, being replaced by LXQT, which is a work-in-progress, but appears to be pretty solid.

The latest WIP version of desktop installer [https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip) replaces SLiM (no longer maintained) with SDDM.  SDDM currently supports Cinnamon, KDE, Lumina, LXDE, LXQT, MATE, and XFCE.  If you run desktop-installer multiple times, installing a different desktop each time and selecting SDDM, you can choose one of them at the SDDM login screen.
