### ISSUE TITLE
Error: x11-fonts/noto-sans does not exist.

### ISSUE THREAD

**Issue by toth3max** [outpaddling/desktop-installer#38]
I'm trying out FreeBSD for the first time and got this error twice today. Once running in Virtual Box installing with XFCE and now as I'm writing this on a laptop choosing to go with KDE. 

I can see in the log just before this error message that it has fetched 6 different noto pkgs and has extracted and installed all of them.

**Comment by outpaddling** [comment]
Thanks for the report!

1. What does "ls /usr/ports/x11-fonts/noto-sans" show?
2. Is this a fresh FreeBSD install, or are you trying desktop installer after fiddling with things manually?
3. Is PORTSDIR set in the environment?

**Comment by outpaddling** [comment]
Based on feedback from #39, you must be using quarterly packages.  The noto-sans and noto-serif meta-ports existed both before and after the latest quarterly branch, but for some reason they're missing from the branch.

I opened a FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282233

This is not a desktop-installer bug, and it's a non-problem since it's only optional fonts. I'll going to close this issue and follow on the FreeBSD PR above.

**Comment by outpaddling** [comment]
The problem was actually an auto-admin script checking out the wrong quarterly ports branch. This has been fixed and the new binary package should be available in a few days.
