### ISSUE TITLE
Error: x11-fonts/noto-serif does not extists.

### ISSUE THREAD

**Issue by sjoerd-visser** [outpaddling/desktop-installer#39]
While installing a completely new fresh 14.1 system and adding the cinnamon desktop this error pops up. It also states: It may not be critical, so we will attempt to continue the setup.
Same error came from noto-sans, but that has already been reported.
I am using a Virtualbox installation.

**Comment by outpaddling** [comment]
Thanks for the report!

1. What does "ls /usr/ports/x11-fonts/noto-sans" show?
2. Is this a fresh FreeBSD install, or are you trying desktop installer after fiddling with things manually?
3. Is PORTSDIR set in the environment?
4. Did you switch to latest packages at the beginning of the desktop-installer run?

**Comment by sjoerd-visser** [comment]
Hi,

my answers are on the next line of your questions.

>     1. What does "ls /usr/ports/x11-fonts/noto-sans" show?
  - $ ls /usr/ports/x-fonts/noto-sans
  - ls: /usr/ports/x11-fonts/noto-sans: No such file or directory
>     2. Is this a fresh FreeBSD install, or are you trying desktop installer after fiddling with things manually?
  - This is a virgin install of FreeBSD 4.1, no fiddling involved
>     3. Is PORTSDIR set in the environment?
  - No, it is not set in the env.
>     4. Did you switch to latest packages at the beginning of the desktop-installer run?
  - No, the installation is based on url: "pkg+https://pkg.FreeBSD.org/${ABI}/quarterly" in /etc/pkg/FreeBSD.conf

I am installing software from packages, not ports. noto-sans exists in the packages, it has been installed.

Regards,
Sjoerd.

**Comment by outpaddling** [comment]
Thanks for the info.  The noto-sans and noto-serif meta-ports existed both before and after the latest quarterly branch, but for some reason they're missing from the branch.

I opened a FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282233

desktop-installer uses auto-install-packages, which can fall back on ports if a binary package install fails, so it will report an invalid port even if you are using binary packages as the primary source.  In fact, it gets the package name from the port Makefile.

This is not a desktop-installer bug, and it's a non-problem since it's only optional fonts.  I'll going to close this issue and follow on the FreeBSD PR above.

**Comment by outpaddling** [comment]
The problem was actually an auto-admin checking out the wrong quarterly ports branch.  This has been fixed and the new binary package should be available in a few days.

**Comment by outpaddling** [comment]
The problem was actually an auto-admin checking out the wrong quarterly ports branch.  This has been fixed and the new binary package should be available in a few days.
